      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}  # you already created this
          files: coverage.xml
          fail_ci_if_error: true
